#!/bin/bash

mapfile -t instances < <( arkmanager list-instances --brief )
needUpdate=()

for inst in "${instances[@]}"; do
  arkmanager checkmodupdate --revstatus "@$inst"
  updateNeeded=$?
  [[ "$updateNeeded" -ne 0 ]] && needUpdate+=( "@$inst" )
done

for upd in "${needUpdate[@]}" ; do
  arkmanager stop --warn "Mod update" "$upd"
  arkmanager update --update-mods --backup "$upd"
  arkmanager start "$upd"
done
