#!/bin/bash

if [ "$MASTER" -eq 1 ]; then
  /usr/local/bin/arkmanager update --warn --backup
  exit 0;
fi

lastUpdate=$(stat --printf="%Y\n" /ark/server/install/ShooterGame/Content/Mods/* | sort -nr | head -n 1)
[[ -f  ~/.arkmodlastcheck ]] && lastCheck=$(cat ~/.arkmodlastcheck)

[[ "$lastUpdate" == "$lastCheck" ]] && exit 0

/usr/local/bin/arkmanager restart --warn --warnreason="Mod Update" --backup --noautoupdate --alwaysrestart
echo "$lastCheck" > ~/.arkmodlastcheck
