#!/bin/bash

/usr/local/bin/arkmanager checkupdate

updateNeeded=$?

[[ "$updateNeeded" -eq 0 ]] && exit 0

/usr/local/bin/arkmanager update --downloadonly
/usr/local/bin/arkmanager stop @all --warn --warnreason="Server update" --saveworld --backup
/usr/local/bin/arkmanager update --no-download

for cfg in /ark/config/instances; do
    # don't need to worry about main instance
    [[ "$cfg" == "main.cfg" ]] && continue

    instName="$(basename -s .cfg ${cfg})"
    shallowPath="$(/usr/local/bin/check-shallow-ark "$cfg")"
    echo "Updating "$instName""
    
    # Not shallow
    if [[ -z "$shallowPath" ]]; then
        # non-shallow instances have to be updated separately
        /usr/local/bin/arkmanager update "@${instName}" --no-download
    else
        /usr/local/bin/ark-gen-shallow "$shallowPath"
        /usr/local/bin/ark-set-shallow-save "$shallowPath" "$instName"
    fi

done

/usr/local/bin/arkmanager start @all --noautoupdate
