#!/usr/bin/env bash

mapfile -t instances < <( arkmanager list-instances --brief )
first="@${instances[0]}"

arkmanager checkupdate "$first"

updateNeeded=$?

[[ "$updateNeeded" -eq 0 ]] && exit 0

arkmanager update --downloadonly "$first"
arkmanager stop --warn --warnreason "Server update" --saveworld @all
arkmanager update --no-download "$first"
arkmanager start @all