#!/bin/bash

arkmanager checkupdate

updateNeeded=$?

[[ "$updateNeeded" -eq 0 ]] && exit 0

arkmanager update --downloadonly
arkmanager stop --warn --warnreason "Server update" --saveworld --backup @all
arkmanager update --no-download
arkmanager start @all
